name: "Sheriff Plan"
description: "Perform a Sheriff plan from GitHub releases"
author: "Craig Anderson"
inputs:
  configDir:
    description: "location of config files"
    required: true
  mode:
    description: "Resources or groups"
    required: true
  subscriptionId:
    description: "Azure subscription ID"
    required: true
  clientId:
    description: "Azure client ID"
    required: false
  tenantId:
    description: "Azure tenant ID"
    required: false
  clientSecret:
    description: "Azure client secret"
    required: false
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node20"
  main: "dist/index.js"
